### ISSUE TITLE
Deleting and/or Moving a widget field fails to provide clickable Save button

### ISSUE THREAD

**Issue by randywsandberg** [Coded-Commerce-LLC/Benchmark-Email-WordPress#27]
**Steps to reproduce:**
1. Log in as admin at https://dev-benchmark-email.pantheonsite.io/wp-admin/widgets.php
2. Drag new instance of Benchmark Email Lite to Sidebar
3. Click to delete First Name field
--> bug

**Expected results:**
Expected Save button to be lite up and clickable.

**Observed results:**
Instead, Saved button remained unclickable. See screenshot below.

**Reproducible?**
Always

**Occurs:**
Latest dev BMEL + MS Edge 42.17134.1.0
Latest dev BMEL + Win Chrome 71.0.3578.98

**Notes:**
Bug also occurs if user MOVES a field. **Moreover, bug also occurs if user DELETES the First Name field (or any field) and then adds back the First Name field.**

**Screenshot taken AFTER deleting a field:**
![capture](https://user-images.githubusercontent.com/19829655/50575095-e63efd80-0daa-11e9-90d9-fd062cce3598.PNG)

**Comment by seanconklin** [comment]
Note: this fix involves a JS file and you will need to use a private browser window or a clean browser to have the change loaded.

**Comment by randywsandberg** [comment]
Cannot reproduce with the latest Dev release of BMEL and Win Chrome 71.0.3578.98. Closing as fixed.
![capture](https://user-images.githubusercontent.com/19829655/50728880-a4cd8b80-10e5-11e9-89df-fac94e78dbd2.PNG)
